### ISSUE TITLE
rollup --watch has no effect.

### ISSUE THREAD

**Issue by kopax** [rollup/rollup-watch#60]
Hi, I would like to report a bug with rollup-watch

**Issue type**

- [x] Bug

**description**

This is my rollup dependencies

```
    "rollup": "^0.49.2",
    "rollup-plugin-babel": "^3.0.2",
    "rollup-plugin-cleanup": "^1.0.1",
    "rollup-plugin-commonjs": "^8.2.0",
    "rollup-plugin-inject": "^2.0.0",
    "rollup-plugin-json": "^2.3.0",
    "rollup-plugin-node-resolve": "^3.0.0",
    "rollup-plugin-replace": "^1.1.1",
    "rollup-plugin-uglify": "^2.0.1",
    "rollup-plugin-visualizer": "^0.3.1",
    "rollup-watch": "^4.3.1",
```

This is my `rollup.config.js`

```jsx harmony
/* eslint-disable flowtype-errors/show-errors, no-console, import/extensions */
import nodeResolve from 'rollup-plugin-node-resolve';
import replace from 'rollup-plugin-replace';
import commonjs from 'rollup-plugin-commonjs';
import inject from 'rollup-plugin-inject';
import babel from 'rollup-plugin-babel';
import json from 'rollup-plugin-json';
import uglify from 'rollup-plugin-uglify';
import cleanup from 'rollup-plugin-cleanup';
import visualizer from 'rollup-plugin-visualizer';
import pkg from './package.json';
const processShim = '\0process-shim';
const prod = process.env.PRODUCTION;
const mode = prod ? 'production' : 'development';

console.log(`Creating ${mode} bundle...`);

const output = prod ?
[
  { file: `dist/${pkg.name}.min.js`, format: 'umd' },
] :
[
  { file: `dist/${pkg.name}.js`, format: 'umd' },
  { file: `dist/${pkg.name}.es.js`, format: 'es' },
];

const plugins = [
  // Unlike Webpack and Browserify, Rollup doesn't automatically shim Node
  // builtins like `process`. This ad-hoc plugin creates a 'virtual module'
  // which includes a shim containing just the parts the bundle needs.
  {
    resolveId(importee) {
      if (importee === processShim) return importee;
      return null;
    },
    load(id) {
      if (id === processShim) return 'export default { argv: [], env: {} }';
      return null;
    },
  },
  nodeResolve(),
  commonjs({
    include: 'node_modules/**',
  }),
  replace({
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
  }),
  inject({
    process: processShim,
  }),
  babel(Object.assign({
    plugins: ['external-helpers'],
    exclude: 'node_modules/**',
  })),
  json(),
  cleanup(),
];

if (prod) plugins.push(uglify(), visualizer({ filename: './bundle-stats.html' }));

export default {
  input: 'src/index.js',
  sourcemap: true,
  name: pkg.name,
  external: ['react', 'react-dom', 'prop-types', 'styled-components'],
  exports: 'named',
  output,
  plugins,
  globals: { react: 'React', 'react-dom': 'ReactDom', 'prop-types': 'PropTypes', 'styled-components': 'styled' },
};
```

**exptected result**

Running `node_modules/rollup/bin/rollup -c --watch` should watch and rebuild my sources.

**actual result**

Running `node_modules/rollup/bin/rollup -c --watch` build and that's it.

**reproduction**

```
me@dev-01:[~/workspace/styled-components/myproject-styled]: node_modules/rollup/bin/rollup -c --watch
Creating development bundle...
me@dev-01:[~/workspace/styled-components/myproject-styled]: node_modules/rollup/bin/rollup -c --watch --environment PRODUCTION
Creating production bundle...
```

If I try running the same command using `npm run` script, I get the following : 

```
> myproject-styled@1.3.0 build:dist:watch /home/dka/workspace/styled-components/myproject-styled
> rollup -c --watch

Creating development bundle...

npm ERR! Linux 4.9.0-3-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:dist:watch"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myproject-styled@1.3.0 build:dist:watch: `rollup -c --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myproject-styled@1.3.0 build:dist:watch script 'rollup -c --watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the myproject-styled package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rollup -c --watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs myproject-styled
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls myproject-styled
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/me/.npm/_logs/2017-08-30T09_13_42_650Z-debug.log

```

And this is the content of `2017-08-30T09_13_42_650Z-debug.log`

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:dist:watch' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose run-script [ 'prebuild:dist:watch',
4 verbose run-script   'build:dist:watch',
4 verbose run-script   'postbuild:dist:watch' ]
5 info lifecycle myproject-styled@1.3.0~prebuild:dist:watch: myproject-styled@1.3.0
6 silly lifecycle myproject-styled@1.3.0~prebuild:dist:watch: no script for prebuild:dist:watch, continuing
7 info lifecycle myproject-styled@1.3.0~build:dist:watch: myproject-styled@1.3.0
8 verbose lifecycle myproject-styled@1.3.0~build:dist:watch: unsafe-perm in lifecycle true
9 verbose lifecycle myproject-styled@1.3.0~build:dist:watch: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/me/workspace/styled-components/myproject-styled/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/me/utils:/usr/local/npm-global/bin
10 verbose lifecycle myproject-styled@1.3.0~build:dist:watch: CWD: /home/me/workspace/styled-components/myproject-styled
11 silly lifecycle myproject-styled@1.3.0~build:dist:watch: Args: [ '-c', 'rollup -c --watch' ]
12 silly lifecycle myproject-styled@1.3.0~build:dist:watch: Returned: code: 1  signal: null
13 info lifecycle myproject-styled@1.3.0~build:dist:watch: Failed to exec build:dist:watch script
14 verbose stack Error: myproject-styled@1.3.0 build:dist:watch: `rollup -c --watch`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid myproject-styled@1.3.0
16 verbose cwd /home/me/workspace/styled-components/myproject-styled
17 error Linux 4.9.0-3-amd64
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:dist:watch"
19 error node v7.10.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error myproject-styled@1.3.0 build:dist:watch: `rollup -c --watch`
23 error Exit status 1
24 error Failed at the myproject-styled@1.3.0 build:dist:watch script 'rollup -c --watch'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the myproject-styled package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     rollup -c --watch
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs myproject-styled
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls myproject-styled
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

```

I have tried with : 

- npm 4 and node 7.10
- npm 5 and node 8

Does anybody know what I am doing wrong ?

**Comment by kopax** [comment]
Closing as retrying with npm 5 and node 8 with the same config did work.
I was probably not using the proper config before. Sorry for the post and I hope this will help others.
